spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://root:YCErNaZZalpDxpCcZ0YN@containers-us-west-150.railway.app:5783/railway}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:YCErNaZZalpDxpCcZ0YN}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5DBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        lob:
          non_contextual_creation: true
      id:
        new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: all
springdoc:
  pathsToMatch: /api/**
PokemonDemo:
  seguridad:
    semilla: 'ea3f350eacbd706321a84585ff9924962c73f2bef5a9d309fe7cbf006d7e4baa'
    duracion: 60000